// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.esdrasbeleza.plugin",
    "name": "comic-sans-plugin",
    "description": "A plugin to make your interface look funnier with Comic Sans.",
    "version": "0.1.0",
    "min_server_version": "5.12.0",
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
